---
fetch_directory: /fetch
cluster: ceph

check_firewall: false
upgrade_ceph_packages: true
ntp_service_enabled: false
ceph_test: false

ceph_stable: true
ceph_mirror: http://download.ceph.com
ceph_stable_key: https://download.ceph.com/keys/release.asc
ceph_stable_release: kraken # ceph stable release
ceph_stable_repo: "{{ ceph_mirror }}/debian-{{ ceph_stable_release }}"

fsid: "{{ cluster_uuid.stdout }}"
generate_fsid: true
cephx: true

common_single_host_mode: true

##########################
# network

monitor_interface: enp0s10
journal_size: 512
public_network: 192.168.50.0/24
cluster_network: "{{ public_network }}"

##########################
# sysconfig

#disable_transparent_hugepage: true
os_tuning_params:
  - { name: kernel.pid_max, value: 4194303 }
  - { name: fs.file-max, value: 26234859 }
  - { name: vm.zone_reclaim_mode, value: 0 }
  - { name: vm.swappiness, value: 10 }
  - { name: vm.min_free_kbytes, value: "{{ vm_min_free_kbytes }}" }

##########################
# workarounds

# https://github.com/ceph/ceph-ansible/issues/1481 not available < 2.3.0
debian_ceph_packages:
  - ceph

##########################
# openstack

# http://ceph.com/pgcalc/

openstack_config: true
openstack_glance_pool:
  name: images
  pg_num: 64
openstack_cinder_pool:
  name: volumes
  pg_num: 256
openstack_nova_pool:
  name: vms
  pg_num: 128
openstack_cinder_backup_pool:
  name: backups
  pg_num: 64

openstack_pools:
  - "{{ openstack_glance_pool }}"
  - "{{ openstack_cinder_pool }}"
  - "{{ openstack_nova_pool }}"
  - "{{ openstack_cinder_backup_pool }}"

openstack_keys:
  - { name: client.nova, value: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool={{ openstack_nova_pool.name }}'" }
  - { name: client.glance, value: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool={{ openstack_glance_pool.name }}'" }
  - { name: client.cinder, value: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool={{ openstack_cinder_pool.name }}, allow rwx pool={{ openstack_nova_pool.name }}, allow rx pool={{ openstack_glance_pool.name }}'"  }
  - { name: client.cinder-backup, value: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool={{ openstack_cinder_backup_pool.name }}'" }

##########################
# ceph

ceph_conf_overrides:
  global:
    enable experimental unrecoverable data corrupting features: bluestore
  osd:
    osd pool default size: 1

##########################
# docker

# NOTE: set this to true when you want to deploy ceph in docker containers
docker: false

containerized_deployment: "{{ docker }}"
ceph_docker_image_tag: tag-build-master-kraken-ubuntu-16.04

mds_containerized_deployment: "{{ containerized_deployment }}"
mgr_containerized_deployment: "{{ containerized_deployment }}"
mon_containerized_deployment: "{{ containerized_deployment }}"
nfs_containerized_deployment: "{{ containerized_deployment }}"
osd_containerized_deployment: "{{ containerized_deployment }}"
rbd_mirror_containerized_deployment: "{{ containerized_deployment }}"
restapi_containerized_deployment: "{{ containerized_deployment }}"
rgw_containerized_deployment: "{{ containerized_deployment }}"

##########################
# scenario

# NOTE: comment the following parametes when you want to deploy ceph in docker containers

bluestore: true
osd_objectstore: bluestore
