---
##########################
# Public roles

- name: betacloud.configuration
  src: git+https://github.com/betacloud/ansible-configuration.git
  version: master

##########################
# Private roles

- name: betacloud.seed
  src: /opt/ansible-galaxy/betacloud.seed.tar.gz
