---
##########################
# Public roles

- name: openstack-ansible-security
  src: git+https://github.com/openstack/openstack-ansible-security.git
  version: 15.1.1

- name: ANXS.hostname
  src: git+https://github.com/ANXS/hostname.git
  version: 4e5ece5a9ad39361fd6b0db02f07fa846d457f98

- name: betacloud.configuration
  src: git+https://github.com/betacloud/ansible-configuration.git
  version: master

- name: betacloud.docker
  src: git+https://github.com/betacloud/ansible-docker.git
  version: master

- name: betacloud.letsencrypt
  src: git+https://github.com/betacloud/ansible-letsencrypt.git
  version: master

- name: betacloud.proxy
  src: git+https://github.com/betacloud/ansible-proxy.git
  version: master

- name: betacloud.docker-cobbler
  src: git+https://github.com/betacloud/ansible-docker-cobbler.git
  version: master
